### ISSUE TITLE
Title in the article looks weird

### ISSUE THREAD

**Issue by filipewl** [redu/help-center#12]
The titles from the article pages are looking weird:

![](http://s3.amazonaws.com/awesome_screenshot/1041571?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1352875462&Signature=RlNrGoellDCVezSSdhndNvXFwHg%3D)

**Comment by jessicabarbalho** [comment]
Closed [here](https://github.com/redu/help-center/commit/6528e4e2bd6d6eacf244eb16dade2413c378eae6)
