### ISSUE TITLE
Spinner is bigger than the button on paginate search

### ISSUE THREAD

**Issue by jessicabarbalho** [redu/help-center#25]

**Comment by filipewl** [comment]
@brunomachado, it's a bug in the bootstrap. I should have corrected it here: https://github.com/redu/ui-components/commit/5d4bf927f6b80a45d4d463b92914fd9f57fd8e07. You need to update the `lib/assets/javascripts/bootstrap-redu.js` in this repo with this new change. To do that, once in `ui-components/contributing`, run the command `grunt concat`. It should create `js/bootstrap-redu.js`. Copy this file and overwrite it with the one in this repo and remember to change `imgPath: 'img/'` with `imgPath: '/assets/'`.
