### ISSUE TITLE
Missing icons in production

### ISSUE THREAD

**Issue by jessicabarbalho** [redu/help-center#28]
1. Manage icon gray (see with @sergiofontes if the topic "Gerenciamento is this icon) 
2. Dev icon gray big

**Comment by brunomachado** [comment]
@jessicabarbalho, these icons are already in ui-components (32x34). Where this icon of Manage is used in the help center?
1. https://raw.github.com/redu/ui-components/contributing/img/icon/manage-gray_32_34.png
2. https://raw.github.com/redu/ui-components/contributing/img/icon/app-gray_32_34.png

**Comment by jessicabarbalho** [comment]
@brunomachado [here](http://ajuda.redu.com.br/guia-do-professor/gerenciamento) But you shuld ask to @sergiofontes because he didn't put any icon on this section in the .pdf
The second is [here](http://ajuda.redu.com.br/guia-do-desenvolvedor/elementos-da-interface-do-usuario) on the title.

**Comment by brunomachado** [comment]
@jessicabarbalho, I talked with Sergio. For the first page is this icon: <a href="https://raw.github.com/redu/ui-components/contributing/img/icon/teacher-gray_32_34.png">teacher-gray_32_34.png</a>. And for the second page is this: <a href="https://raw.github.com/redu/ui-components/contributing/img/icon/app-gray_32_34.png">app-gray_32_34.png</a>.

**Comment by jessicabarbalho** [comment]
Ok @brunomachado these icons are missing. But see this [page](http://ajuda.redu.com.br/guia-do-professor) The item "Gerenciamento" doesn't have icon

**Comment by jessicabarbalho** [comment]
The item for "gerenciamento" (manage-gray_16_18) is missing too

**Comment by jessicabarbalho** [comment]
Closed in #29
