### ISSUE TITLE
Header link does not have the correct href

### ISSUE THREAD

**Issue by julianalucena** [redu/help-center#34]
The header showed below, does not link us to the correct section. This header is located in a article's show.

![Screen Shot 2013-03-05 at 8 37 06 AM](https://f.cloud.github.com/assets/387579/221061/16d2b30c-8589-11e2-8375-3d9b964a6ecb.png)

When I click on the link above, it does not link me to guide's page. After the click, I stay in the same page.

**Comment by jessicabarbalho** [comment]
@brunomachado do you remmember what action this link does? I think the designer decided it.

**Comment by brunomachado** [comment]
I don't remember, @jessicabarbalho. Need ask again to @sergiofontes.
