### ISSUE TITLE
Footer is not fixed in page's inferior part

### ISSUE THREAD

**Issue by julianalucena** [redu/help-center#35]
![Screen Shot 2013-03-05 at 8 39 33 AM](https://f.cloud.github.com/assets/387579/221072/73620140-8589-11e2-9973-ae3dacf06f29.png)

**Comment by brunomachado** [comment]
@filipewl, adicionei aquela técnica do sticky footer aqui. É isso mesmo, não é?

**Comment by julianalucena** [comment]
Por que esta solução ainda não está em produção?

![Screen Shot 2013-03-19 at 8 14 25 AM](https://f.cloud.github.com/assets/387579/275339/4be9a656-9086-11e2-8a76-99251dc12002.png)

**Comment by filipewl** [comment]
@julianalucena quem foi o engraçadinho responsável por dar deploy neste repo que ainda não o fez? Aí se eu pego... `:@`

**Comment by jessicabarbalho** [comment]
@fltiago ficou de dar deploy ontem.
